import { useMemo, useState } from 'react';
import { useSettingsDocument } from '../../hooks/use-settings-document';
import { jsonValuesEqual } from '../../utils/json-values-equal';
import { saveCameraConfiguration, saveMotionConfiguration } from '../../services/device-service';
import type { DeviceSnapshot } from '../../types/devices';
import {
  DEFAULT_RECIPE_DEFAULTS, DEFAULT_SYSTEM_POLICY, DEFAULT_WORKSTATION_PROFILE,
  type RecipeDefaults, type SystemPolicy, type WorkstationProfile,
} from '../../types/settings-documents';

export type VersionedSectionId = 'overview' | 'acquisition' | 'motion' | 'inspection' | 'compute' | 'research' | 'data' | 'integrations' | 'notifications' | 'security';

interface SettingsDocumentSectionProps {
  accessToken?: string;
  sectionId: VersionedSectionId;
  workstationId: string;
  deviceSnapshot?: DeviceSnapshot | null;
  onOpenHardware?: () => void;
}

function NumberField({ label, value, min = 0, unit, onChange }: { label: string; value: number; min?: number; unit?: string; onChange: (value: number) => void }) {
  return <label><span>{label}</span><div className="settings-input-unit"><input type="number" min={min} value={value} onChange={(event) => onChange(Number(event.target.value))} />{unit && <small>{unit}</small>}</div></label>;
}

function ToggleField({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) {
  return <label className="settings-toggle"><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} /><span>{label}</span></label>;
}

function WorkstationFields({ sectionId, value, onChange, snapshot, onOpenHardware }: {
  sectionId: VersionedSectionId; value: WorkstationProfile; onChange: (value: WorkstationProfile) => void;
  snapshot?: DeviceSnapshot | null; onOpenHardware?: () => void;
}) {
  const patch = (next: Partial<WorkstationProfile>) => onChange({ ...value, ...next });
  if (sectionId === 'overview') return <>
    <div className="settings-group"><h3>Station identity</h3><div className="settings-grid"><label><span>Station display name</span><input value={value.stationDisplayName} onChange={(event) => patch({ stationDisplayName: event.target.value })} /></label><label><span>Deployment mode</span><select value={value.deploymentMode} onChange={(event) => patch({ deploymentMode: event.target.value as WorkstationProfile['deploymentMode'] })}><option value="research">Research</option><option value="simulation">Simulation</option><option value="hardware-pilot">Hardware pilot</option><option value="production">Production</option></select></label></div></div>
    <div className="settings-health-grid"><span><strong>Camera</strong>{snapshot?.devices.camera.status ?? 'unknown'}</span><span><strong>Motion</strong>{snapshot?.devices.motion.status ?? 'unknown'}</span><span><strong>Calibration</strong>{value.calibration.calibrationId ? 'referenced' : 'missing'}</span><span><strong>Recipe</strong>rev-c-mainboard</span></div>
    {onOpenHardware && <button className="studio-secondary-button" type="button" onClick={onOpenHardware}>Open Hardware diagnostics</button>}
  </>;
  if (sectionId === 'acquisition') return <div className="settings-group"><h3>Acquisition and calibration</h3>{snapshot?.devices.camera.status === 'ready' && value.camera ? <div className="settings-grid"><label><span>Camera profile</span><input value={value.cameraProfileName} onChange={(event) => patch({ cameraProfileName: event.target.value })} /></label><label><span>Camera ID</span><input value={value.camera.cameraId} onChange={(event) => patch({ camera: { ...value.camera!, cameraId: event.target.value } })} /></label><label><span>Sensor mode</span><input value={value.camera.sensorMode} onChange={(event) => patch({ camera: { ...value.camera!, sensorMode: event.target.value } })} /></label><NumberField label="Exposure" value={value.camera.exposureMicroseconds} min={1} unit="μs" onChange={(next) => patch({ camera: { ...value.camera!, exposureMicroseconds: next } })} /><NumberField label="Analog gain" value={value.camera.analogGain} min={0.1} onChange={(next) => patch({ camera: { ...value.camera!, analogGain: next } })} /><label><span>Calibration ID</span><input value={value.calibration.calibrationId ?? ''} onChange={(event) => patch({ calibration: { ...value.calibration, calibrationId: event.target.value || null } })} /></label><ToggleField label="Block production when calibration is invalid" checked={value.calibration.blockProductionWhenInvalid} onChange={(next) => patch({ calibration: { ...value.calibration, blockProductionWhenInvalid: next } })} /></div> : snapshot?.devices.camera.status === 'ready' && snapshot.cameraConfiguration ? <><p>Desired camera profile is empty. Import observed adapter values to start a draft.</p><button type="button" className="studio-secondary-button" onClick={() => patch({ camera: structuredClone(snapshot.cameraConfiguration) })}>Use observed camera configuration</button></> : <p className="settings-degraded">Camera controls omitted because adapter is not ready. Use Hardware for preview, test capture, and calibration acquisition.</p>}</div>;
  return <div className="settings-group"><h3>Motion and I/O profile</h3>{snapshot?.devices.motion.status === 'ready' && value.motion ? <div className="settings-grid"><label><span>Motion profile</span><input value={value.motionProfileName} onChange={(event) => patch({ motionProfileName: event.target.value })} /></label><NumberField label="Maximum velocity" value={value.motion.maximumVelocityMillimetersPerSecond} min={0.1} unit="mm/s" onChange={(next) => patch({ motion: { ...value.motion!, maximumVelocityMillimetersPerSecond: next } })} /><NumberField label="Maximum acceleration" value={value.motion.maximumAccelerationMillimetersPerSecondSquared} min={0.1} unit="mm/s²" onChange={(next) => patch({ motion: { ...value.motion!, maximumAccelerationMillimetersPerSecondSquared: next } })} /><NumberField label="Settle time" value={value.motion.settleMilliseconds} unit="ms" onChange={(next) => patch({ motion: { ...value.motion!, settleMilliseconds: next } })} /><NumberField label="Pose tolerance" value={value.poseToleranceMillimeters} min={0.001} unit="mm" onChange={(next) => patch({ poseToleranceMillimeters: next })} /><NumberField label="Trigger timeout" value={value.triggerTimeoutMilliseconds} min={100} unit="ms" onChange={(next) => patch({ triggerTimeoutMilliseconds: next })} /></div> : snapshot?.devices.motion.status === 'ready' && snapshot.motionConfiguration ? <><p>Desired motion profile is empty. Import observed adapter values to start a draft.</p><button type="button" className="studio-secondary-button" onClick={() => patch({ motion: structuredClone(snapshot.motionConfiguration) })}>Use observed motion configuration</button></> : <p className="settings-degraded">Motion controls omitted because adapter is not ready. Home, Move, Stop, Clear fault, and interlocks remain in Hardware and MCU.</p>}</div>;
}

function RecipeFields({ value, onChange }: { value: RecipeDefaults; onChange: (value: RecipeDefaults) => void }) {
  const patch = (next: Partial<RecipeDefaults>) => onChange({ ...value, ...next });
  return <div className="settings-group"><h3>Inspection policy</h3><div className="settings-grid"><label><span>Active recipe</span><input value={value.activeRecipeSlug} onChange={(event) => patch({ activeRecipeSlug: event.target.value })} /></label><label><span>Decision policy</span><select value={value.decisionPolicy} onChange={(event) => patch({ decisionPolicy: event.target.value as RecipeDefaults['decisionPolicy'] })}><option value="strict">Strict</option><option value="review-borderline">Review borderline</option><option value="research">Research</option></select></label><NumberField label="Run timeout" value={value.runTimeoutSeconds} min={1} unit="seconds" onChange={(next) => patch({ runTimeoutSeconds: next })} /><NumberField label="Maximum retries" value={value.maximumRetries} onChange={(next) => patch({ maximumRetries: next })} /><ToggleField label="Require serial" checked={value.serialRequired} onChange={(next) => patch({ serialRequired: next })} /><ToggleField label="Require lot" checked={value.lotRequired} onChange={(next) => patch({ lotRequired: next })} /><ToggleField label="Retain decision evidence" checked={value.evidenceRequired} onChange={(next) => patch({ evidenceRequired: next })} /><label><span>Defect taxonomy</span><input value={value.defectTaxonomy} onChange={(event) => patch({ defectTaxonomy: event.target.value })} /></label></div></div>;
}

function SystemFields({ sectionId, value, onChange }: { sectionId: VersionedSectionId; value: SystemPolicy; onChange: (value: SystemPolicy) => void }) {
  const patch = <K extends keyof SystemPolicy>(key: K, next: SystemPolicy[K]) => onChange({ ...value, [key]: next });
  if (sectionId === 'compute') return <div className="settings-group"><h3>Execution limits</h3><div className="settings-grid"><label><span>Execution target</span><select value={value.compute.executionTarget} onChange={(event) => patch('compute', { ...value.compute, executionTarget: event.target.value as SystemPolicy['compute']['executionTarget'] })}><option value="cpu">CPU</option><option value="cuda">CUDA GPU</option><option value="jetson">Jetson</option><option value="remote-worker">Remote worker</option></select></label><NumberField label="Concurrent inspections" value={value.compute.maximumConcurrentInspections} min={1} onChange={(next) => patch('compute', { ...value.compute, maximumConcurrentInspections: next })} /><NumberField label="Research jobs" value={value.compute.maximumResearchJobs} onChange={(next) => patch('compute', { ...value.compute, maximumResearchJobs: next })} /><NumberField label="Memory limit" value={value.compute.memoryLimitMegabytes} min={512} unit="MiB" onChange={(next) => patch('compute', { ...value.compute, memoryLimitMegabytes: next })} /><ToggleField label="Deterministic execution" checked={value.compute.deterministicExecution} onChange={(next) => patch('compute', { ...value.compute, deterministicExecution: next })} /></div></div>;
  if (sectionId === 'research') return <div className="settings-group"><h3>Research and model defaults</h3><div className="settings-grid"><label><span>Artifact storage</span><select value={value.research.artifactStoragePolicy} onChange={(event) => patch('research', { ...value.research, artifactStoragePolicy: event.target.value as SystemPolicy['research']['artifactStoragePolicy'] })}><option value="filesystem">Managed filesystem</option><option value="object-storage">Object storage</option></select></label><label><span>Tracking backend</span><select value={value.research.trackingBackend} onChange={(event) => patch('research', { ...value.research, trackingBackend: event.target.value as 'internal' | 'mlflow' })}><option value="internal">Internal</option><option value="mlflow">MLflow</option></select></label><NumberField label="Retained checkpoints" value={value.research.checkpointRetentionCount} min={1} onChange={(next) => patch('research', { ...value.research, checkpointRetentionCount: next })} /><ToggleField label="Require validation evidence" checked={value.research.requireValidationEvidence} onChange={(next) => patch('research', { ...value.research, requireValidationEvidence: next })} /></div></div>;
  if (sectionId === 'data') return <div className="settings-group"><h3>Data and retention</h3><div className="settings-grid"><NumberField label="Preview retention" value={value.retention.previewDays} unit="days" onChange={(next) => patch('retention', { ...value.retention, previewDays: next })} /><NumberField label="Raw capture retention" value={value.retention.rawCaptureDays} unit="days" onChange={(next) => patch('retention', { ...value.retention, rawCaptureDays: next })} /><NumberField label="Result evidence retention" value={value.retention.resultEvidenceDays} min={1} unit="days" onChange={(next) => patch('retention', { ...value.retention, resultEvidenceDays: next })} /><NumberField label="Storage quota" value={value.retention.storageQuotaGigabytes} min={1} unit="GiB" onChange={(next) => patch('retention', { ...value.retention, storageQuotaGigabytes: next })} /><NumberField label="Disk pressure" value={value.retention.diskPressurePercent} min={50} unit="%" onChange={(next) => patch('retention', { ...value.retention, diskPressurePercent: next })} /><ToggleField label="Legal or quality hold" checked={value.retention.legalHold} onChange={(next) => patch('retention', { ...value.retention, legalHold: next })} /></div><p>Portable JSON uses SHA-256; it does not replace PostgreSQL-native disaster-recovery backup.</p></div>;
  if (sectionId === 'integrations') return <div className="settings-group"><h3>Factory integrations</h3><div className="settings-grid"><ToggleField label="PLC" checked={value.integrations.plcEnabled} onChange={(next) => patch('integrations', { ...value.integrations, plcEnabled: next })} /><ToggleField label="MES" checked={value.integrations.mesEnabled} onChange={(next) => patch('integrations', { ...value.integrations, mesEnabled: next })} /><label><span>MES endpoint</span><input type="url" value={value.integrations.mesEndpoint} onChange={(event) => patch('integrations', { ...value.integrations, mesEndpoint: event.target.value })} /></label><label><span>Secret reference</span><input value={value.integrations.mesSecretReference ?? ''} onChange={(event) => patch('integrations', { ...value.integrations, mesSecretReference: event.target.value || null })} /><small>Plaintext secrets are rejected.</small></label><ToggleField label="IPC-CFX" checked={value.integrations.ipcCfxEnabled} onChange={(next) => patch('integrations', { ...value.integrations, ipcCfxEnabled: next })} /><ToggleField label="OPC UA" checked={value.integrations.opcUaEnabled} onChange={(next) => patch('integrations', { ...value.integrations, opcUaEnabled: next })} /></div></div>;
  if (sectionId === 'notifications') return <div className="settings-group"><h3>Notification policy</h3><div className="settings-grid"><ToggleField label="Machine faults" checked={value.notifications.machineFaults} onChange={(next) => patch('notifications', { ...value.notifications, machineFaults: next })} /><ToggleField label="Adapter degradation" checked={value.notifications.adapterDegradation} onChange={(next) => patch('notifications', { ...value.notifications, adapterDegradation: next })} /><ToggleField label="Calibration expiry" checked={value.notifications.calibrationExpiry} onChange={(next) => patch('notifications', { ...value.notifications, calibrationExpiry: next })} /><ToggleField label="Storage pressure" checked={value.notifications.storagePressure} onChange={(next) => patch('notifications', { ...value.notifications, storagePressure: next })} /><ToggleField label="Model drift" checked={value.notifications.modelDrift} onChange={(next) => patch('notifications', { ...value.notifications, modelDrift: next })} /><NumberField label="Rate limit" value={value.notifications.minimumIntervalSeconds} min={1} unit="seconds" onChange={(next) => patch('notifications', { ...value.notifications, minimumIntervalSeconds: next })} /></div></div>;
  return <div className="settings-group"><h3>Security, audit, and updates</h3><div className="settings-admin-card"><span>Initial identity</span><strong>AOI Administrator</strong><small>Role-management UI remains deferred.</small></div><div className="settings-grid"><NumberField label="Session expiry" value={value.securityUpdates.sessionMinutes} min={5} unit="minutes" onChange={(next) => patch('securityUpdates', { ...value.securityUpdates, sessionMinutes: next })} /><label><span>Update channel</span><select value={value.securityUpdates.updateChannel} onChange={(event) => patch('securityUpdates', { ...value.securityUpdates, updateChannel: event.target.value as SystemPolicy['securityUpdates']['updateChannel'] })}><option value="stable">Stable</option><option value="pilot">Pilot</option><option value="disabled">Disabled</option></select></label><label><span>Maintenance window</span><input value={value.securityUpdates.maintenanceWindow} onChange={(event) => patch('securityUpdates', { ...value.securityUpdates, maintenanceWindow: event.target.value })} /></label><ToggleField label="Require signed updates" checked={value.securityUpdates.signedUpdatesRequired} onChange={(next) => patch('securityUpdates', { ...value.securityUpdates, signedUpdatesRequired: next })} /><ToggleField label="Allow audit export" checked={value.securityUpdates.auditExportEnabled} onChange={(next) => patch('securityUpdates', { ...value.securityUpdates, auditExportEnabled: next })} /></div></div>;
}

export function SettingsDocumentSection({ accessToken, sectionId, workstationId, deviceSnapshot, onOpenHardware }: SettingsDocumentSectionProps) {
  const initialProfile = useMemo(() => ({ ...structuredClone(DEFAULT_WORKSTATION_PROFILE), camera: deviceSnapshot?.cameraConfiguration ?? null, motion: deviceSnapshot?.motionConfiguration ?? null }), [workstationId]);
  const workstation = useSettingsDocument(accessToken, { scope: 'workstation', subjectId: workstationId, documentKey: 'workstation-profile' }, initialProfile);
  const recipe = useSettingsDocument(accessToken, { scope: 'recipe', subjectId: 'rev-c-mainboard', documentKey: 'recipe-defaults' }, DEFAULT_RECIPE_DEFAULTS);
  const system = useSettingsDocument(accessToken, { scope: 'system', subjectId: 'local', documentKey: 'system-policy' }, DEFAULT_SYSTEM_POLICY);
  const scope = sectionId === 'inspection' ? 'Recipe' : ['compute', 'research', 'data', 'integrations', 'notifications', 'security'].includes(sectionId) ? 'System' : 'Workstation';
  const lifecycle = scope === 'Recipe' ? recipe : scope === 'System' ? system : workstation;
  const [reason, setReason] = useState('Update approved settings');
  const [message, setMessage] = useState('');

  const applyProfile = async (profile: WorkstationProfile) => {
    if (!accessToken) return;
    if (profile.camera) {
      if (deviceSnapshot?.devices.camera.status !== 'ready') throw new Error('Camera adapter is not ready.');
      const observed = await saveCameraConfiguration(accessToken, profile.camera);
      if (!jsonValuesEqual(observed, profile.camera)) throw new Error('Camera observed state does not match desired profile.');
    }
    if (profile.motion) {
      if (deviceSnapshot?.devices.motion.status !== 'ready') throw new Error('Motion adapter is not ready.');
      const observed = await saveMotionConfiguration(accessToken, profile.motion);
      if (!jsonValuesEqual(observed, profile.motion)) throw new Error('Motion observed state does not match desired profile.');
    }
  };

  const save = async () => {
    setMessage('');
    if (scope === 'Workstation') await workstation.save(reason, applyProfile);
    else if (scope === 'Recipe') await recipe.save(reason);
    else await system.save(reason);
    setMessage('Settings validated, versioned, and activated.');
  };
  const rollback = async (target: number) => {
    if (window.confirm(`Create a new immutable version from R${target}?`)) {
      if (scope === 'Workstation') await workstation.rollback(target, reason);
      else if (scope === 'Recipe') await recipe.rollback(target, reason);
      else await system.rollback(target, reason);
    }
  };

  return <>
    <div className="settings-ledger"><span><small>Scope</small><strong>{scope}</strong></span><span><small>Revision</small><strong>R{lifecycle.revision}</strong></span><span><small>Active</small><strong>{lifecycle.activeRevision === null ? 'Not applied' : `R${lifecycle.activeRevision}`}</strong></span><span><small>Draft</small><strong>{lifecycle.isDirty ? 'Changed' : 'Clean'}</strong></span></div>
    <div className="settings-form__body">{scope === 'Workstation' ? <WorkstationFields sectionId={sectionId} value={workstation.draft} onChange={workstation.setDraft} snapshot={deviceSnapshot} onOpenHardware={onOpenHardware} /> : scope === 'Recipe' ? <RecipeFields value={recipe.draft} onChange={recipe.setDraft} /> : <SystemFields sectionId={sectionId} value={system.draft} onChange={system.setDraft} />}
      {lifecycle.conflict && <div className="settings-conflict" role="alert"><strong>Revision conflict</strong><p>Server is at R{lifecycle.conflict.currentRevision ?? '?'}. Reload current version before applying.</p><button type="button" onClick={() => void lifecycle.reload()}>Reload current version</button></div>}
      <details className="settings-history"><summary>Version history</summary>{lifecycle.history.versions.length === 0 ? <p>No persisted versions yet.</p> : <ol>{lifecycle.history.versions.map((version) => <li key={version.revision}><span><strong>R{version.revision}</strong>{version.reason || 'No reason'}<small>{new Date(version.createdAt).toLocaleString()}</small></span>{version.revision !== lifecycle.revision && <button type="button" onClick={() => void rollback(version.revision)}>Rollback</button>}</li>)}</ol>}</details>
    </div>
    <div className="settings-form__actions"><label><span>Change reason</span><input value={reason} maxLength={2000} onChange={(event) => setReason(event.target.value)} /></label><div>{lifecycle.error && <span className="settings-error" role="alert">{lifecycle.error}</span>}{message && <span role="status">{message}</span>}</div><button className="studio-secondary-button" type="button" disabled={!lifecycle.isDirty} onClick={lifecycle.discard}>Discard</button><button className="studio-primary-button" type="button" disabled={!lifecycle.isDirty || !reason.trim() || lifecycle.status === 'Applying'} onClick={() => void save().catch(() => undefined)}>{lifecycle.status === 'Applying' ? 'Applying…' : 'Validate & apply'}</button></div>
  </>;
}