import type { WorkspaceView } from '../types/workspace';

export type HelpLanguage = 'vi' | 'en';
export type HelpIllustration = 'overview' | 'workflow' | 'research' | 'models' | 'workspace';

export interface HelpSection {
  id: string;
  title: string;
  eyebrow: string;
  summary: string;
  steps: string[];
  tips: string[];
  view?: WorkspaceView;
  viewLabel?: string;
  illustration: HelpIllustration;
}

export interface HelpDocument {
  searchLabel: string;
  searchPlaceholder: string;
  contentsLabel: string;
  noResults: string;
  openLabel: string;
  diagramLabel: string;
  sections: HelpSection[];
}

export const HELP_CONTENT: Record<HelpLanguage, HelpDocument> = {
  vi: {
    searchLabel: 'Tìm trong hướng dẫn',
    searchPlaceholder: 'Ví dụ: workflow, research, champion, camera…',
    contentsLabel: 'Mục lục hướng dẫn',
    noResults: 'Không tìm thấy nội dung phù hợp. Hãy thử từ khóa ngắn hơn.',
    openLabel: 'Mở workspace',
    diagramLabel: 'Minh họa quy trình AOI Studio',
    sections: [
      {
        id: 'quick-start', title: 'Bắt đầu nhanh', eyebrow: 'Tổng quan', illustration: 'overview',
        summary: 'Luồng chuẩn đi từ thiết bị và dữ liệu đến workflow, nghiên cứu mô hình, đăng ký phiên bản và chạy kiểm tra sản xuất.',
        steps: ['Mở Hardware, chọn đúng workstation, nhấn Refresh và chỉ tiếp tục khi camera/motion không ở trạng thái unavailable.', 'Mở Camera rig, chọn nguồn ảnh, đặt exposure/gain và xác nhận ảnh không mờ, cháy sáng hoặc thiếu ROI.', 'Mở Dataset, nhập ảnh, gán category/nhãn, xử lý file lỗi và chốt train/validation/test.', 'Mở Workflow, tạo chuỗi acquisition → xử lý → suy luận/đánh giá → output; nối đúng kiểu cổng và sửa hết validation issue.', 'Với node trainable, chọn dataset và execution target, tạo job rồi chờ completed; ghi lại Run ID.', 'Trong Research, kiểm tra lineage, metric, environment và artifact; so sánh ít nhất hai run phù hợp.', 'Trong Models, đăng ký artifact verified thành version bất biến, kiểm thử Candidate rồi mới duyệt Champion.', 'Quay lại Dashboard, xác nhận recipe/workflow và Champion trước khi chạy inspection.'],
        tips: ['Không bỏ qua bước kiểm tra đầu vào và schema.', 'Mỗi run, artifact và model version đều cần truy vết được.'],
      },
      {
        id: 'dashboard', title: 'Dashboard', eyebrow: 'Operate', view: 'dashboard', viewLabel: 'Dashboard', illustration: 'workspace',
        summary: 'Theo dõi trạng thái máy, I/O, recipe đang hoạt động và kết quả inspection gần nhất trong một màn hình.',
        steps: ['Chọn đúng workstation và chờ trạng thái tải xong.', 'Kiểm tra Ready/degraded/unavailable; mở Hardware nếu có thành phần degraded và không chạy nếu unavailable.', 'Đọc input an toàn như emergency stop, cửa và cảm biến hiện diện; I/O là dữ liệu boolean on/off.', 'Xác nhận recipe, workflow revision và model đang hoạt động.', 'Kiểm tra output ở trạng thái an toàn, sau đó nhấn Run đúng một lần và chờ khi running.', 'Đọc PASS là đạt, REVIEW là cần người xác nhận, FAIL là lỗi/không đạt; mở ảnh và output node để điều tra.', 'Đối chiếu timestamp, board/lot, Run ID và model version trong Database khi kết quả bất thường.'],
        tips: ['Dùng Refresh I/O khi tín hiệu vật lý thay đổi.', 'Không chạy khi emergency stop hoặc cửa an toàn chưa hợp lệ.'],
      },
      {
        id: 'hardware', title: 'Hardware', eyebrow: 'Operate', view: 'hardware', viewLabel: 'Hardware', illustration: 'workspace',
        summary: 'Kiểm tra kết nối thiết bị, khả năng hệ thống và trạng thái I/O trước khi hiệu chỉnh hoặc chạy inspection.',
        steps: ['Chọn workstation và phân biệt mode hardware (thiết bị thật) với simulation (mô phỏng).', 'Nhấn Refresh rồi đọc riêng health camera, motion và MCU/I/O: ready, degraded hoặc unavailable.', 'Đối chiếu service, implementation, protocol version và capabilities với thiết bị đã lắp.', 'Camera configuration gồm camera ID/sensor mode dạng chuỗi và exposure/gain dạng số; kiểm tra giới hạn trước khi Apply.', 'Motion configuration gồm trục, tọa độ, giới hạn, vận tốc/gia tốc dạng số; xác nhận homing trước khi jog.', 'Input/output là boolean; chỉ thử output trong chế độ bảo trì an toàn.', 'Sau khi thay cáp, driver hoặc cấu hình, Refresh và xác nhận thiết bị trở về ready.'],
        tips: ['Giải quyết lỗi phần cứng trước lỗi workflow.', 'Không ép output nếu chưa hiểu tác động lên máy.'],
      },
      {
        id: 'camera', title: 'Camera rig', eyebrow: 'Operate', view: 'camera-manager', viewLabel: 'Camera rig', illustration: 'workspace',
        summary: 'Chọn nguồn ảnh, hiệu chỉnh camera và lưu cấu hình chụp ổn định cho workstation.',
        steps: ['Chọn đúng view/camera và xác nhận nguồn là camera thật hay replay source.', 'Đặt sensor mode/resolution (width × height) và pixel format khớp node acquisition.', 'Đặt exposure dạng số microsecond: tăng khi tối, giảm khi vùng sáng bị clipping.', 'Đặt analog gain dạng số ở mức thấp nhất vẫn đủ sáng để hạn chế nhiễu.', 'Căn toàn bộ ROI trong ảnh; ROI là tập vùng tọa độ, image là ma trận pixel.', 'Preview board OK, board lỗi và biến thiên vị trí/ánh sáng thực tế.', 'Calibrate transform pixel–tọa độ máy nếu workflow cần, lưu rồi chụp lại để xác nhận cấu hình đã áp dụng.'],
        tips: ['Giữ ánh sáng và khoảng cách camera nhất quán.', 'Ảnh mờ hoặc cháy sáng sẽ làm sai cả training lẫn inspection.'],
      },
      {
        id: 'workflow', title: 'Workflow', eyebrow: 'Build', view: 'workflow-editor', viewLabel: 'Workflow', illustration: 'workflow',
        summary: 'Workflow là đồ thị có hướng không chu trình (typed DAG): mỗi node nhận input có kiểu, xử lý parameter và phát output tương thích.',
        steps: ['Mở đúng recipe; đọc recipe name, version, revision và xử lý migration notice trước khi sửa graph.', 'Thêm node acquisition từ Algorithm catalog, chọn node và đọc documentation, capabilities, execution target cùng mọi input/output trong Inspector.', 'Cấu hình parameter theo kiểu: boolean bật/tắt; integer số nguyên; number số thực; text chuỗi; select chỉ nhận option; json là array/object; reference trỏ tài nguyên; model-reference trỏ model/version.', 'Thêm các node ROI/transform, preprocessing, feature, detection/anomaly, decision và output theo mục tiêu; đặt display name rõ nghĩa.', 'Nối output nguồn vào input đích đúng data type. Input required phải có nguồn; input không variadic chỉ nhận một connection.', 'Các kiểu cổng gồm generic, boolean, image, image-set, mask, roi-set, keypoints, contours, features, detections, anomaly-map, score, transform và decision.', 'image là một ảnh; image-set là nhiều ảnh; mask là nhãn theo pixel; roi-set là các vùng; keypoints là tọa độ điểm; contours là đường bao.', 'features là vector; detections là đối tượng/vị trí/lớp; anomaly-map là bản đồ điểm; score là số; transform đổi hệ tọa độ; decision là kết luận.', 'Dùng data edge cho dữ liệu và control edge cho điều khiển. Data graph không được có cycle; control cycle được hỗ trợ phải có maxTraversals hữu hạn.', 'Sửa từng lỗi type-mismatch, missing-required-input, invalid-parameter, generic-type-conflict, duplicate ID/edge, cycle hoặc execution-order-mismatch.', 'Nhấn Auto order, đọc Execution order rail và bảo đảm mọi node đứng sau dependency.', 'Preview/test từng nhánh nếu được hỗ trợ; kiểm tra schema, kích thước, đơn vị và miền giá trị output trước node kế tiếp.', 'Với node trainable, mở Training, chọn dataset input và local-cpu/local-gpu/adapter, cấu hình parameter rồi tạo job.', 'Theo dõi queued → running → completed. Nếu failed, đọc error và sửa data/parameter/resource rồi tạo run mới; cancelled không tạo source phát hành.', 'Ghi Run ID completed để mở Research. Save khi không còn issue; nếu stale revision/conflict, reload bản server rồi áp dụng lại thay đổi có chủ đích.'],
        tips: ['Dùng tên output rõ nghĩa và kiểm tra preview sau từng nhánh.', 'Run ID từ training là cầu nối sang Research; không đăng ký artifact chưa hoàn tất.'],
      },
      {
        id: 'dataset', title: 'Dataset', eyebrow: 'Build', view: 'dataset', viewLabel: 'Dataset', illustration: 'workspace',
        summary: 'Quản lý ảnh, nhãn, phân vùng train/validation/test và phiên bản dữ liệu dùng cho nghiên cứu.',
        steps: ['Tạo/chọn dataset đúng sản phẩm và mô tả nguồn, điều kiện chụp, phạm vi sử dụng.', 'Tạo category trước khi import để một lỗi không có nhiều cách viết.', 'Nhập ảnh, chờ upload rồi loại file hỏng, sai resolution, trùng hoặc sai board.', 'Gán nhãn theo bài toán: class cho classification, bounding box cho detection, mask cho segmentation; anomaly cần mẫu OK đại diện và lỗi để đánh giá.', 'Chạy Validation, mở issue theo category/filename và sửa hoặc loại mẫu.', 'Kiểm tra số lượng, cân bằng lớp và biến thiên lot/ánh sáng/vị trí.', 'Chia train để học, validation để chọn parameter/threshold, test để đánh giá cuối; không để mẫu gần trùng qua nhiều split.', 'Đóng băng dataset version trước training; mọi thay đổi ảnh/nhãn phải tạo version mới.'],
        tips: ['Không dùng ảnh test để huấn luyện.', 'Ghi lại dataset version trong mọi research run.'],
      },
      {
        id: 'database', title: 'Database', eyebrow: 'Review', view: 'database', viewLabel: 'Database', illustration: 'workspace',
        summary: 'Tra cứu lịch sử inspection, board, lot, recipe, kết quả và bằng chứng phục vụ truy vết.',
        steps: ['Chọn khoảng thời gian và workstation trước, sau đó thêm board/lot/result để lọc hẹp.', 'Mở record và xác nhận timestamp, board ID, lot ID, recipe/version cùng trạng thái.', 'Xem ảnh, output node, score dạng số, decision và error được lưu cùng inspection.', 'Đối chiếu workflow revision, Research Run ID, model name/version/alias và artifact hash.', 'So sánh các board liền trước/sau để phân biệt lỗi đơn lẻ với drift thiết bị/dữ liệu.', 'Export theo quyền và giữ nguyên ID/timestamp; bằng chứng lịch sử là append-only.'],
        tips: ['Dùng bộ lọc hẹp trước khi xuất dữ liệu lớn.', 'Không chỉnh sửa bằng chứng lịch sử ngoài quy trình quản trị.'],
      },
      {
        id: 'research', title: 'Research', eyebrow: 'Review', view: 'research', viewLabel: 'Research', illustration: 'research',
        summary: 'Tìm, đọc, tái lập và so sánh training run bằng toàn bộ bằng chứng, không chỉ metric cao nhất.',
        steps: ['Lấy Run ID từ Training panel; tìm bằng Run ID đầy đủ hoặc experiment ID/name, code revision, execution target.', 'Đọc status trước: queued đang chờ, running chưa xong, completed mới được tạo model version, failed/cancelled chỉ dùng chẩn đoán.', 'Xác nhận experimentId đúng bài toán, executionTarget đúng môi trường và codeRevision đúng commit đã review.', 'Đọc nodeVersions (map tên → version); khác package/manifest có thể làm hai run không còn tương đương.', 'Đọc datasetVersions theo từng input và split; không so metric giữa dữ liệu khác nhau mà không ghi chú.', 'Đọc randomSeeds (map tên → số nguyên). Cùng code/data/parameter/seed hỗ trợ tái lập nhưng phần cứng/thư viện vẫn có thể gây sai khác nhỏ.', 'Mở Parameters and environment; parameters, environment, resources là object JSON có boolean, number, string, array hoặc object lồng nhau.', 'Đọc metric dạng map tên → number theo task, split, unit và chiều tối ưu; accuracy/F1 thường tăng là tốt, loss/error/latency thường giảm là tốt.', 'Nếu failed, đọc Failure diagnostics cùng resource/environment, sửa nguyên nhân rồi tạo run mới; không sửa bằng chứng cũ.', 'Mở Output artifacts; kiểm tra name, mediaType, byteLength, SHA-256, verified và bảo đảm artifact thuộc chính run.', 'Chọn checkbox ít nhất hai run, nhấn Compare selected và đối chiếu metric, dataset, revision, seed, parameter, environment, runtime.', 'Mở reproducibility manifest để lưu lineage. Chỉ qua Models khi completed, artifact verified, tiêu chí đạt và compatibility được xác nhận.', 'Nếu quá 20 run, dùng Show more hoặc thu hẹp Search thay vì duyệt toàn bộ lịch sử.'],
        tips: ['Failed run vẫn hữu ích để đọc Failure diagnostics.', 'Metric cao không đủ: phải xác nhận dữ liệu, compatibility và điều kiện chạy đại diện.'],
      },
      {
        id: 'models', title: 'Models', eyebrow: 'Review', view: 'models', viewLabel: 'Models', illustration: 'models',
        summary: 'Biến artifact completed thành version bất biến và quản trị Candidate → Champion → Rollback bằng reason cùng audit event.',
        steps: ['Chọn New model nếu chưa có model logic; nhập name duy nhất và description nêu task, sản phẩm, camera/ROI, mục đích.', 'Chọn Existing model để thêm version; không tạo tên gần giống chỉ để thay thế version cũ.', 'Chọn source run completed. Nếu không thấy run, quay lại Research kiểm tra status.', 'Chọn artifact thuộc run và chỉ dùng artifact verified; kiểm tra name, media type, byte length và SHA-256.', 'Nhập validation evidence dạng JSON object: dataset/split, metric, threshold, latency, workstation đích, reviewer và ngày kiểm thử.', 'Nếu là ONNX, khai báo format onnx, runtime onnxruntime, runtimeVersion, inputSchema/outputSchema, preprocessing và postprocessing.', 'Mỗi tensor cần name, dtype và shape. Dtype hỗ trợ float32, float16, int64, int32, uint8, bool; shape có số hoặc tên chiều động.', 'Nhấn Register version; hệ thống tạo version number mới và giữ hash, không ghi đè version cũ.', 'Mở version, kiểm tra source run, task, framework, status, schema, evidence và hash; dùng Open source run để đối chiếu.', 'Promote to candidate sau kiểm tra kỹ thuật ở môi trường đích; nhập reason cụ thể rồi Confirm.', 'Chạy acceptance test với Candidate; chỉ Promote to champion khi đạt tiêu chí và đã xác nhận đúng version.', 'Champion là alias sản xuất; promotion chỉ đổi con trỏ alias, không sửa artifact/version.', 'Khi regression, chọn Rollback champion; đọc preview currentVersion → targetVersion và previewEventId, nhập lý do rồi Confirm.', 'Mở Promotion history để kiểm tra action, alias, previousVersion, nextVersion, reason, actor và createdAt.'],
        tips: ['Candidate là bản đang đánh giá; Champion là bản production được workflow phân giải.', 'Không thay thế file của version cũ; luôn tạo version mới để giữ truy vết.'],
      },
      {
        id: 'settings', title: 'Settings', eyebrow: 'System', view: 'settings', viewLabel: 'Settings', illustration: 'workspace',
        summary: 'Quản lý cấu hình workstation, compute, research, data, integration, notification và security theo phạm vi.',
        steps: ['Chọn section và scope user/workstation/recipe/system; kiểm tra subject ID trước khi sửa.', 'Cấu hình appearance/locale bằng enum/string; region và timezone phải tương thích.', 'Kiểm tra workstation/compute/research/data: ID, execution target, giới hạn số, directory và retention.', 'Kiểm tra integration/notification/security: endpoint, boolean policy và quyền.', 'Sửa từng giá trị, xử lý validation warning và không rời trang khi còn dirty nếu muốn giữ thay đổi.', 'Nhấn Save, chờ thành công rồi xác nhận revision/activation; mở Hardware nếu thay đổi liên quan thiết bị.'],
        tips: ['Không thay policy production trong lúc inspection đang chạy.', 'Ghi lại lý do khi thay đổi cấu hình ảnh hưởng kết quả.'],
      },
      {
        id: 'end-to-end', title: 'Workflow → Research → Models', eyebrow: 'Quy trình mô hình', illustration: 'overview',
        summary: 'Đây là đường đi bắt buộc để một thuật toán trainable trở thành phiên bản production có thể truy vết.',
        steps: ['Workflow — chốt recipe/revision, node version, typed ports, parameter, dataset version/split và execution target.', 'Workflow — sửa hết graph/schema issue, Save rồi tạo training job từ đúng Inspector.', 'Workflow — theo dõi queued/running; giữ diagnostics của failed/cancelled; ghi Run ID khi completed.', 'Research — kiểm tra code revision, node/dataset versions, seed, parameters, environment và resources.', 'Research — đọc metric theo split/task, kiểm tra leakage và so sánh ít nhất hai run trên cùng cơ sở.', 'Research — xác nhận artifact thuộc run, media type/size đúng, SHA-256 đầy đủ và verified; lưu manifest.', 'Gate Research → Models — yêu cầu completed, tiêu chí chất lượng/latency đạt, artifact verified và schema/runtime tương thích.', 'Models — tạo/chọn model, chọn run/artifact, nhập evidence/contract và đăng ký immutable version.', 'Models — promote Candidate có reason, chạy acceptance trên môi trường đích rồi mới promote Champion.', 'Operate — xác nhận recipe/model-reference dùng đúng Champion và theo dõi regression/drift.', 'Rollback — đọc preview, đưa Champion về version trước với reason; giữ nguyên version lỗi để audit.'],
        tips: ['Không có completed run thì Models không cho chọn source.', 'Luôn kiểm tra source run và artifact SHA-256 trước promotion.'],
      },
    ],
  },
  en: {
    searchLabel: 'Search the guide', searchPlaceholder: 'For example: workflow, research, champion, camera…',
    contentsLabel: 'Guide contents', noResults: 'No matching guidance. Try a shorter search term.', openLabel: 'Open workspace',
    diagramLabel: 'AOI Studio process illustration',
    sections: [
      { id: 'quick-start', title: 'Quick start', eyebrow: 'Overview', illustration: 'overview', summary: 'The controlled journey moves from devices and data through workflow, research, model registration, and traceable inspection.', steps: ['Select the workstation in Hardware, refresh it, and continue only when camera and motion are available.', 'Configure Camera rig and verify sharp, correctly exposed images containing every ROI.', 'Import and label Dataset samples, resolve invalid files, and define train/validation/test splits.', 'Build an acquisition → processing → inference/evaluation → output Workflow; connect compatible ports and resolve all issues.', 'For a trainable node, select dataset and target, create a job, wait for completed, and record its Run ID.', 'Review lineage, metrics, environment, and artifacts in Research; compare at least two suitable runs.', 'Register a verified artifact as an immutable Model version, validate Candidate, and approve Champion.', 'Verify the intended recipe, workflow, and Champion on Dashboard before inspection.'], tips: ['Do not skip input, schema, or safety checks.', 'Record recipe revision, dataset version, Run ID, artifact SHA-256, and model version.'] },
      { id: 'dashboard', title: 'Dashboard', eyebrow: 'Operate', view: 'dashboard', viewLabel: 'Dashboard', illustration: 'workspace', summary: 'Monitor machine health, I/O, the active recipe, and the latest inspection result.', steps: ['Select the workstation and wait for status to load.', 'Read ready/degraded/unavailable; open Hardware for degraded components and do not run while unavailable.', 'Verify emergency stop, door, and presence inputs; digital I/O values are boolean on/off.', 'Confirm the active recipe, workflow revision, and model.', 'Verify safe outputs, press Run once, and wait while running.', 'Interpret PASS as accepted, REVIEW as human review, and FAIL as a defect or unmet condition.', 'For anomalies, inspect images/node outputs and cross-check timestamp, board/lot, Run ID, and model version in Database.'], tips: ['Refresh I/O after physical signals change.', 'Never run with an emergency stop or unsafe door state.'] },
      { id: 'hardware', title: 'Hardware', eyebrow: 'Operate', view: 'hardware', viewLabel: 'Hardware', illustration: 'workspace', summary: 'Verify device connectivity, capabilities, and physical I/O before calibration or inspection.', steps: ['Select the workstation and distinguish physical hardware mode from simulation.', 'Refresh and inspect camera, motion, and MCU/I/O ready/degraded/unavailable states separately.', 'Compare service, implementation, protocol version, and capabilities with installed devices.', 'Verify string camera ID/sensor mode and numeric exposure/gain before applying.', 'Verify numeric motion axes, coordinates, limits, velocity/acceleration, and homing state.', 'Treat I/O as booleans and test outputs only in safe maintenance mode.', 'Refresh after cable, driver, or configuration changes and confirm ready.'], tips: ['Resolve hardware faults before workflow faults.', 'Do not force an output without understanding its machine effect.'] },
      { id: 'camera', title: 'Camera rig', eyebrow: 'Operate', view: 'camera-manager', viewLabel: 'Camera rig', illustration: 'workspace', summary: 'Select an image source, calibrate the camera, and save a stable acquisition setup.', steps: ['Select the correct view/camera and distinguish hardware from replay.', 'Set width × height sensor mode and pixel format to match acquisition.', 'Adjust numeric exposure in microseconds to avoid dark or clipped regions.', 'Use the lowest numeric analog gain that provides sufficient brightness.', 'Keep every ROI coordinate region inside the image pixel matrix.', 'Preview good/defective boards across realistic position and lighting variation.', 'Calibrate pixel-to-machine transform when required, save, and capture again to verify applied values.'], tips: ['Keep lighting and camera distance consistent.', 'Blurred or clipped images compromise both training and inspection.'] },
      { id: 'workflow', title: 'Workflow', eyebrow: 'Build', view: 'workflow-editor', viewLabel: 'Workflow', illustration: 'workflow', summary: 'A Workflow is a typed directed acyclic graph: nodes consume typed inputs, apply parameters, and publish compatible outputs.', steps: ['Open the recipe and review name, version, revision, and migration notices.', 'Add acquisition from Algorithm catalog; select it and read documentation, capabilities, target, inputs, and outputs in Inspector.', 'Configure parameter types: boolean toggle, integer whole number, number decimal, text string, select listed option, JSON array/object, reference resource, or model-reference model/version.', 'Add ROI/transform, preprocessing, feature, detection/anomaly, decision, and output nodes with meaningful names.', 'Connect compatible output/input data types. Supply required inputs; a non-variadic input accepts one edge.', 'Port types are generic, boolean, image, image-set, mask, roi-set, keypoints, contours, features, detections, anomaly-map, score, transform, and decision.', 'image is one image; image-set is many; mask is pixel labels; roi-set is regions; keypoints are points; contours are boundaries.', 'features are vectors; detections are located/classified objects; anomaly-map is a score map; score is numeric; transform maps coordinates; decision is a conclusion.', 'Use data edges for data and control edges for execution control. The data graph cannot cycle; supported control cycles need finite maxTraversals.', 'Resolve type mismatch, missing required input, invalid parameter, generic conflict, duplicate ID/edge, cycle, and execution-order issues.', 'Run Auto order and confirm every node follows its dependencies in Execution order.', 'Preview supported branches and verify output schema, dimensions, units, and ranges.', 'For trainable nodes, choose dataset inputs and local-cpu/local-gpu/adapter, configure parameters, and create a job.', 'Follow queued → running → completed. Diagnose failed and create a new run; cancelled is not a release source.', 'Record the completed Run ID for Research. Save only after validation; reload and deliberately reapply changes after a stale revision.'], tips: ['Name nodes/outputs by business meaning and test branches before building a large graph.', 'Release production model references through Models, never during a running inspection.'] },
      { id: 'dataset', title: 'Dataset', eyebrow: 'Build', view: 'dataset', viewLabel: 'Dataset', illustration: 'workspace', summary: 'Manage images, labels, train/validation/test splits, and research data versions.', steps: ['Create/select the product dataset and document source, capture conditions, and intended use.', 'Define categories before import to prevent duplicate defect names.', 'Import images and remove corrupt, wrong-resolution, duplicate, or wrong-product files.', 'Use image classes for classification, boxes for detection, masks for segmentation, and representative OK/defect evidence for anomaly evaluation.', 'Run validation and resolve issues by category and filename.', 'Review class balance and lot/lighting/position variation.', 'Use train for fitting, validation for parameter/threshold choice, and test for final evaluation; keep near-duplicates in one split.', 'Freeze a version before training; image or label changes require a new version.'], tips: ['Never train on the test split.', 'Record the dataset version in every run.'] },
      { id: 'database', title: 'Database', eyebrow: 'Review', view: 'database', viewLabel: 'Database', illustration: 'workspace', summary: 'Find inspection history, boards, lots, recipes, results, and traceability evidence.', steps: ['Filter by a short time range and workstation, then board/lot/result.', 'Open a record and verify timestamp, board/lot IDs, recipe/version, and result enum.', 'Review images, node outputs, numeric score, decision, and errors.', 'Cross-check workflow revision, Research Run ID, model name/version/alias, and artifact hash.', 'Compare neighboring boards to distinguish isolated defects from device/data drift.', 'Export under authorization while preserving IDs and timestamps; history is append-only.'], tips: ['Narrow filters before large exports.', 'Do not alter historical evidence outside governance procedures.'] },
      { id: 'research', title: 'Research', eyebrow: 'Review', view: 'research', viewLabel: 'Research', illustration: 'research', summary: 'Find, interpret, reproduce, and compare runs using complete evidence rather than one headline metric.', steps: ['Copy the Workflow Training Run ID; search it or experiment ID/name, code revision, or execution target.', 'Read status first: queued waits, running is incomplete, completed can source a model, and failed/cancelled is diagnostic only.', 'Verify experimentId, intended executionTarget, and reviewed codeRevision.', 'Review nodeVersions (name → version); package/manifest differences can make runs incomparable.', 'Verify datasetVersions and splits; document comparisons that use different data.', 'Review randomSeeds (name → integer). Matching code/data/parameters/seed supports reproduction, though runtimes can remain nondeterministic.', 'Open Parameters and environment; parameters, environment, and resources are JSON objects with booleans, numbers, strings, arrays, or nested objects.', 'Interpret numeric metrics by task, split, unit, and direction: accuracy/F1 commonly rise, while loss/error/latency commonly fall.', 'For failed runs, inspect diagnostics/resources/environment and create a corrected run instead of editing old evidence.', 'Verify artifact name, media type, byte length, SHA-256, verified state, source run, and output contract.', 'Select at least two runs and compare metrics, data, revision, seed, parameters, environment, and runtime.', 'Open the reproducibility manifest. Proceed only with completed status, verified artifact, accepted criteria, and compatibility.', 'Use Show more for pages beyond 20 or narrow Search.'], tips: ['Keep failed runs as diagnostic evidence.', 'Reject high metrics with leakage, unrepresentative data, unverified artifacts, or incompatible runtime.'] },
      { id: 'models', title: 'Models', eyebrow: 'Review', view: 'models', viewLabel: 'Models', illustration: 'models', summary: 'Turn completed-run artifacts into immutable versions and govern Candidate → Champion → Rollback with audited reasons.', steps: ['Choose New model and enter a stable unique name plus task/product/camera/ROI purpose, or Existing model to add a version.', 'Select a completed source run; return to Research when it is absent.', 'Select a verified artifact from that run and inspect name, media type, byte length, and SHA-256.', 'Enter validation evidence as a JSON object: dataset/split, metrics, threshold, latency, target workstation, reviewer, and date.', 'For ONNX, define format onnx, runtime onnxruntime, runtimeVersion, input/output schemas, preprocessing, and postprocessing.', 'Define tensor name, dtype, and shape. Supported dtypes are float32, float16, int64, int32, uint8, and bool; shape accepts fixed numbers or dynamic names.', 'Register the version; a new version number and hash are retained without overwriting old versions.', 'Review source run, task, framework, status, schemas, evidence, and hash; open the source run to cross-check Research.', 'Promote to candidate after target-environment technical validation; enter a specific reason and confirm.', 'Run Candidate acceptance tests; promote the approved version to champion with a reason.', 'Champion is a production alias pointer; promotion never edits artifact bytes.', 'For regression, preview currentVersion → targetVersion and previewEventId, enter the incident reason, then confirm rollback.', 'Review action, alias, previous/next versions, reason, actor, and timestamp in Promotion history.'], tips: ['Create a new version for packaged preprocessing or threshold changes.', 'Verified proves artifact integrity, not production approval.'] },
      { id: 'settings', title: 'Settings', eyebrow: 'System', view: 'settings', viewLabel: 'Settings', illustration: 'workspace', summary: 'Manage scoped workstation, compute, research, data, integration, notification, and security settings.', steps: ['Choose the section and user/workstation/recipe/system scope; verify subject ID.', 'Configure appearance/locale enum and string values; keep region and timezone compatible.', 'Review workstation/compute/research/data IDs, execution target, numeric limits, directories, and retention.', 'Review integration/notification/security endpoints, boolean policies, and permissions.', 'Edit fields, clear validation warnings, and do not leave while dirty when changes must be retained.', 'Save, wait for success, and verify revision/activation; open Hardware for device-related changes.'], tips: ['Do not change production policy during inspection.', 'Record reasons and revisions for changes that affect results.'] },
      { id: 'end-to-end', title: 'Workflow → Research → Models', eyebrow: 'Model workflow', illustration: 'overview', summary: 'The complete path from a trainable node to a production Champion, with a gate at every handoff.', steps: ['Workflow: fix recipe/revision, node versions, typed ports, parameters, dataset version/splits, and target.', 'Clear graph/schema issues, save, and create training from the correct Inspector.', 'Preserve failed/cancelled diagnostics; record the Run ID only after completed.', 'Research: verify code revision, node/data versions, seeds, parameters, environment, and resources.', 'Interpret metrics by task/split, check leakage, and compare at least two runs on a common basis.', 'Verify artifact source, media type/size, SHA-256, verified state, and reproducibility manifest.', 'Gate to Models only with completed status, accepted quality/latency, verified artifact, and compatible schemas/runtime.', 'Register an immutable version with evidence and contract.', 'Promote Candidate with a reason, run target-environment acceptance, then approve Champion.', 'Confirm Workflow/recipe resolves to the intended Champion and monitor drift/regression.', 'For incidents, inspect rollback preview, restore the previous Champion with a reason, and preserve the faulty version.'], tips: ['Models has no eligible source without a completed run and verified artifact.', 'Stop promotion whenever any ID, version, or hash does not match.'] },
    ],
  },
};